#pragma once

// Name: DBZ-Kakarot, Version: 4.21.2


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_8C83A9A94908DD75C474FE830A229DF8
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_8C83A9A94908DD75C474FE830A229DF8_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_7FE744BB4A33B0B255897FA0816B6F94
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_7FE744BB4A33B0B255897FA0816B6F94_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_6C418AE849214B9CEF1EF7872671A52B
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_6C418AE849214B9CEF1EF7872671A52B_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_87F143AE415395E1D25E65925284CB97
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_87F143AE415395E1D25E65925284CB97_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_F62CC79C45819CC46AFC198F83F7A77C
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_F62CC79C45819CC46AFC198F83F7A77C_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_019518004A69FFED3A4B429D2DD4050D
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_019518004A69FFED3A4B429D2DD4050D_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_D8A353BF42F04B354BA01B81BA2E937A
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_D8A353BF42F04B354BA01B81BA2E937A_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_8335EC474E6B2412C84D1BB852E11254
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_8335EC474E6B2412C84D1BB852E11254_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_EE92E1BA444CBB9B9708E0AAAFB3A2AA
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_EE92E1BA444CBB9B9708E0AAAFB3A2AA_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_7010D34744136EA3639C0E8186E01624
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_7010D34744136EA3639C0E8186E01624_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_2D75F140435C487A2FFC6CBCD7E7C337
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_2D75F140435C487A2FFC6CBCD7E7C337_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_ECB7765A462C0697B5DC40914C09FB10
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_ECB7765A462C0697B5DC40914C09FB10_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_296757084DF263AEB3BC55A33B234ECD
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_296757084DF263AEB3BC55A33B234ECD_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_AF385665495E0BFBCDD97A8F452A056B
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_AF385665495E0BFBCDD97A8F452A056B_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TwoBoneIK_A320B76A42C371CE7ADD948A4C3FA08D
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TwoBoneIK_A320B76A42C371CE7ADD948A4C3FA08D_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TwoBoneIK_7EB6DB5846089033B7A3BFA90E27DE25
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TwoBoneIK_7EB6DB5846089033B7A3BFA90E27DE25_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_BlendListByBool_66677ABB46B4FF83A33E969A47E97278
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_BlendListByBool_66677ABB46B4FF83A33E969A47E97278_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_B31521B54C42ECB4EE525695419EC745
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_B31521B54C42ECB4EE525695419EC745_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_3DFC75D847534F9F54BE85BD4B10B560
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_3DFC75D847534F9F54BE85BD4B10B560_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_CBCCF84744C6BEAD2BA568ABE337745C
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_CBCCF84744C6BEAD2BA568ABE337745C_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_0BAE200B4D0CCB7EB8AACAA5EC99E468
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_0BAE200B4D0CCB7EB8AACAA5EC99E468_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_FFC38A664A93B2E55B5FC194D66D463A
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_FFC38A664A93B2E55B5FC194D66D463A_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.BlueprintUpdateAnimation
struct UDinosaur_AnimBP_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.AnimNotify_StartState
struct UDinosaur_AnimBP_C_AnimNotify_StartState_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.AnimNotify_EndState
struct UDinosaur_AnimBP_C_AnimNotify_EndState_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_B2ABF2014A6222B5482F7C94B819BA3E
struct UDinosaur_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Dinosaur_AnimBP_AnimGraphNode_TransitionResult_B2ABF2014A6222B5482F7C94B819BA3E_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.AnimNotify_StartRunLoop
struct UDinosaur_AnimBP_C_AnimNotify_StartRunLoop_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.AnimNotify_EndRunLoop
struct UDinosaur_AnimBP_C_AnimNotify_EndRunLoop_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.AnimNotify_StartDead
struct UDinosaur_AnimBP_C_AnimNotify_StartDead_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.AnimNotify_EndDead
struct UDinosaur_AnimBP_C_AnimNotify_EndDead_Params
{
};

// Function Dinosaur_AnimBP.Dinosaur_AnimBP_C.ExecuteUbergraph_Dinosaur_AnimBP
struct UDinosaur_AnimBP_C_ExecuteUbergraph_Dinosaur_AnimBP_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
