#pragma once

// Name: DBZ-Kakarot, Version: 4.21.2


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_C1EB7EE54C6C54205736ED829AD32453
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_C1EB7EE54C6C54205736ED829AD32453_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_050F555E40512CC28F34C7B023EC6330
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_050F555E40512CC28F34C7B023EC6330_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_BBC6BE6240B6A8D21D52A38FDB176438
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_BBC6BE6240B6A8D21D52A38FDB176438_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_6851EFB34A58C11EE25D35A0FA93B951
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_6851EFB34A58C11EE25D35A0FA93B951_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_00B052984D94C756245908A5AF6B495E
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_00B052984D94C756245908A5AF6B495E_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_000EDEA34F85F057350C0191C437925C
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_000EDEA34F85F057350C0191C437925C_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_C9A505414578B5BE919FA1A5CE050E39
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_C9A505414578B5BE919FA1A5CE050E39_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByBool_0F3E92BE4617E0A6D16A3D9B65818438
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByBool_0F3E92BE4617E0A6D16A3D9B65818438_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendSpacePlayer_B54D822E481A9D15877E649DAF2C952A
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendSpacePlayer_B54D822E481A9D15877E649DAF2C952A_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_LayeredBoneBlend_83778D674B96742EA7BC78ABD9D653EA
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_LayeredBoneBlend_83778D674B96742EA7BC78ABD9D653EA_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_LayeredBoneBlend_3DEE25D247DC1BAF9DFC69A26BC1FFDB
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_LayeredBoneBlend_3DEE25D247DC1BAF9DFC69A26BC1FFDB_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_A1E9B9534622458A42A216B2A8573231
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_A1E9B9534622458A42A216B2A8573231_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByBool_3E67060F4CEE00825C365A9DBEA7BD72
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByBool_3E67060F4CEE00825C365A9DBEA7BD72_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByBool_47F513A9479C3FD4EB37BAACC7C3466E
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByBool_47F513A9479C3FD4EB37BAACC7C3466E_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_984F2C694989026BF6E186BF03ABEFA7
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_984F2C694989026BF6E186BF03ABEFA7_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_0AD760DC4E3017C9E94BC6982097AEEF
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_0AD760DC4E3017C9E94BC6982097AEEF_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_2FA2EDAA42320E38E1AB478D03B0A309
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_2FA2EDAA42320E38E1AB478D03B0A309_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_BDB8B73A4764A148A3B5F5AD9749B526
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_BDB8B73A4764A148A3B5F5AD9749B526_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_3134A7DF4F82F81755B2D2AB86BC8DD3
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AT_TalkAnimGraphNode_LookAt_3134A7DF4F82F81755B2D2AB86BC8DD3_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_2D279DAA466B0DBC6CB5A0B85E2ED23F
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_2D279DAA466B0DBC6CB5A0B85E2ED23F_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_8511E7684DA247FB009E34A2648A1633
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_8511E7684DA247FB009E34A2648A1633_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_E5D280B04E358A02C982AD99C83A7971
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_E5D280B04E358A02C982AD99C83A7971_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_2E89D23A4CD9486E8C9F03A050BC054C
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_2E89D23A4CD9486E8C9F03A050BC054C_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_E7031B9446FB84EB7CD057B6F539F7E0
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_E7031B9446FB84EB7CD057B6F539F7E0_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_992DBC73415BC079FC73E688E06B6928
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_992DBC73415BC079FC73E688E06B6928_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_EF05318047A4338B92A620AAD3662225
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_EF05318047A4338B92A620AAD3662225_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_D8A362864765E388737CC68D32767A27
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_D8A362864765E388737CC68D32767A27_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_EA8B593848ED2B3F8F296A91664698BC
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_BlendListByEnum_EA8B593848ED2B3F8F296A91664698BC_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_4525859F4E6D0CCDA5EA789546917FFF
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_4525859F4E6D0CCDA5EA789546917FFF_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_DFCEF77A4F1C5242828F998E2A13AAA5
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_DFCEF77A4F1C5242828F998E2A13AAA5_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_5B89A6A24FEC6DFC0280E2BF271FBCAA
struct UTownTalkAnimBlueprint_C_EvaluateGraphExposedInputs_ExecuteUbergraph_TownTalkAnimBlueprint_AnimGraphNode_TransitionResult_5B89A6A24FEC6DFC0280E2BF271FBCAA_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.BlueprintUpdateAnimation
struct UTownTalkAnimBlueprint_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.AnimNotify_OnLeftIdlingSequence
struct UTownTalkAnimBlueprint_C_AnimNotify_OnLeftIdlingSequence_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.AnimNotify_OnIdlingLoopCountUp
struct UTownTalkAnimBlueprint_C_AnimNotify_OnIdlingLoopCountUp_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.AnimNotify_ResetNearPlayer
struct UTownTalkAnimBlueprint_C_AnimNotify_ResetNearPlayer_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.BlueprintInitializeAnimation
struct UTownTalkAnimBlueprint_C_BlueprintInitializeAnimation_Params
{
};

// Function TownTalkAnimBlueprint.TownTalkAnimBlueprint_C.ExecuteUbergraph_TownTalkAnimBlueprint
struct UTownTalkAnimBlueprint_C_ExecuteUbergraph_TownTalkAnimBlueprint_Params
{
	int                                                EntryPoint;                                                // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
